[project]
name = "image-manager"
requires-python = ">= 3.8"
author = {name = "Alex C Warren", email = "alexcwarren.info@gmail.com"}
description = "Modify a batch of given image files."
readme = "README.md"
license = {file = "LICENSE"}

[tool.black]
line-length = 87